server:
  port: 8081
  servlet:
    session:
      cookie:
        #防止cookie重复，冲突会导致登录验证不通过
        name: OAUTH2-CLIENT-SESSIONID01
oauth2-server-url: http://localhost:8080

security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key

